[package]
name = "example_enums"
version = "0.1.0"
authors = ["Jämes Ménétrey <james@menetrey.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"example_maths" =  { path = "../example_maths" }