[package]
name = "example_app"
version = "0.1.0"
authors = ["Jämes Ménétrey <james@menetrey.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"example_enums" = { path = "../example_enums" }